In [2]:
import numpy as np

In [8]:
import numpy as np
text1="idal"
text2="ediel"
dist=np.zeros((len(text1)+1,len(text2)+1))

dist[0,:]=np.arange(len(text2)+1)
dist[:,0]=np.arange(len(text1)+1)
print(dist)
for i in range(len(text1)+1):
    for j in range(len(text2)+1):
        if(text1[i-1]==text2[j-1]):
            dist[i,j]=dist[i-1,j-1]
        else:
            dist[i,j]=min(dist[i-1,j]+1,dist[i-1,j]+1,dist[i-1,j-1]+2)
print(dist)

[[0. 1. 2. 3. 4. 5.]
 [1. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0.]]
[[0. 1. 1. 1. 1. 0.]
 [1. 2. 2. 1. 2. 1.]
 [2. 3. 2. 2. 3. 2.]
 [3. 4. 3. 3. 4. 3.]
 [3. 5. 4. 4. 5. 4.]]
